/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.jimulabs.googlemusicmock;

public final class R {
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layoutManager=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int reverseLayout=0x7f010002;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int spanCount=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int stackFromEnd=0x7f010003;
    }
    public static final class color {
        public static final int yellow=0x7f070000;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 
 Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively). 
         */
        public static final int activity_horizontal_margin=0x7f050001;
        public static final int activity_vertical_margin=0x7f050002;
        public static final int item_touch_helper_max_drag_scroll_per_frame=0x7f050000;
    }
    public static final class drawable {
        public static final int broken_distance_sutro=0x7f020000;
        public static final int cylinders_chris_zabriskie=0x7f020001;
        public static final int direct_to_video_chris_zabriskie=0x7f020002;
        public static final int green_circle=0x7f020003;
        public static final int ic_launcher=0x7f020004;
        public static final int ic_pause_24dp=0x7f020005;
        public static final int ic_volume_up_24dp=0x7f020006;
        public static final int keep_it_together_guster=0x7f020007;
        public static final int mean_something_kinder_than_wolves=0x7f020008;
        public static final int playing_with_scratches_ruckus_roboticus=0x7f020009;
        public static final int please_sondre_lerche=0x7f02000a;
        public static final int the_carpenter_avett_brothers=0x7f02000b;
    }
    public static final class id {
        public static final int action_search=0x7f06000e;
        public static final int action_settings=0x7f06000d;
        public static final int album_art=0x7f060002;
        public static final int album_list=0x7f06000b;
        public static final int album_title=0x7f060004;
        public static final int artist=0x7f060005;
        public static final int detail_container=0x7f060001;
        public static final int fab=0x7f060006;
        public static final int item_touch_helper_previous_elevation=0x7f060000;
        public static final int length=0x7f06000a;
        public static final int textView=0x7f06000c;
        public static final int title_panel=0x7f060003;
        public static final int track_name=0x7f060009;
        public static final int track_panel=0x7f060007;
        public static final int volume=0x7f060008;
    }
    public static final class layout {
        public static final int activity_album_detail=0x7f030000;
        public static final int activity_album_list=0x7f030001;
        public static final int album_grid_item=0x7f030002;
        public static final int view_animation=0x7f030003;
    }
    public static final class menu {
        public static final int menu_album_detail=0x7f0a0000;
        public static final int menu_album_list=0x7f0a0001;
    }
    public static final class string {
        public static final int action_settings=0x7f080001;
        public static final int app_name=0x7f080000;
        public static final int title_activity_album_detail=0x7f080002;
    }
    public static final class style {
        /**  Base application theme. 
         */
        public static final int AppTheme=0x7f090000;
        public static final int AppTheme_Dark=0x7f090001;
    }
    public static final class transition {
        public static final int album_detail_enter=0x7f040000;
        public static final int album_detail_return=0x7f040001;
    }
    public static final class styleable {
        /** Attributes that can be used with a RecyclerView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #RecyclerView_android_orientation android:orientation}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_layoutManager com.jimulabs.googlemusicmock:layoutManager}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_reverseLayout com.jimulabs.googlemusicmock:reverseLayout}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_spanCount com.jimulabs.googlemusicmock:spanCount}</code></td><td></td></tr>
           <tr><td><code>{@link #RecyclerView_stackFromEnd com.jimulabs.googlemusicmock:stackFromEnd}</code></td><td></td></tr>
           </table>
           @see #RecyclerView_android_orientation
           @see #RecyclerView_layoutManager
           @see #RecyclerView_reverseLayout
           @see #RecyclerView_spanCount
           @see #RecyclerView_stackFromEnd
         */
        public static final int[] RecyclerView = {
            0x010100c4, 0x7f010000, 0x7f010001, 0x7f010002,
            0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#orientation}
          attribute's value can be found in the {@link #RecyclerView} array.
          @attr name android:orientation
        */
        public static final int RecyclerView_android_orientation = 0;
        /**
          <p>This symbol is the offset where the {@link com.jimulabs.googlemusicmock.R.attr#layoutManager}
          attribute's value can be found in the {@link #RecyclerView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.jimulabs.googlemusicmock:layoutManager
        */
        public static final int RecyclerView_layoutManager = 1;
        /**
          <p>This symbol is the offset where the {@link com.jimulabs.googlemusicmock.R.attr#reverseLayout}
          attribute's value can be found in the {@link #RecyclerView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.jimulabs.googlemusicmock:reverseLayout
        */
        public static final int RecyclerView_reverseLayout = 3;
        /**
          <p>This symbol is the offset where the {@link com.jimulabs.googlemusicmock.R.attr#spanCount}
          attribute's value can be found in the {@link #RecyclerView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.jimulabs.googlemusicmock:spanCount
        */
        public static final int RecyclerView_spanCount = 2;
        /**
          <p>This symbol is the offset where the {@link com.jimulabs.googlemusicmock.R.attr#stackFromEnd}
          attribute's value can be found in the {@link #RecyclerView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.jimulabs.googlemusicmock:stackFromEnd
        */
        public static final int RecyclerView_stackFromEnd = 4;
    };
}
